fastlane_version '2.53.1'

platform :ios do
	desc 'Build the prod iOS application.'
	lane :prod do |options|
		match(type: 'appstore')
		increment_build_number_in_plist(
			 xcodeproj: '{DIR_TO_XPROJECT}',
			 target:"{SCHEME_NAME}"
		)
		update_code_signing_settings(
	        use_automatic_signing: false,
	        path: "{DIR_TO_XPROJECT}"
		)
		build_app(
			workspace: "{DIR_TO_XWORKSPACE}",
			scheme: "{SCHEME_NAME}",
			clean: true,
			export_method: "app-store"
        )
		pilot(skip_waiting_for_build_processing:true)
	end

	lane :devices do
  		register_devices(devices_file: "./fastlane/devices.txt")
  		match(type: "development", force_for_new_devices: true)
	end
end

